
# Preferences and Utility

How can we model people's choices?

I. Axioms of Rational Choice

  1) Completeness: For any $A \text{ and } B$ either  
        a) $A \succ B$,   
        b) $A \prec B$, or  
        c) $A \sim B$  
        
    Not paralyzed by indecision.
    
  2) Transitivity
  
     If  $A \succ B$ and  $B \succ C$, then  $A \succ C$
     
  3) Continuity
  
     If  $A \succ B$, then "close to $A$"  $\succ B$  
     
     Technical detail that allows us to take derivatives.
     
II. Utility - Ranking of Preferences

  + If  $A \succ B$ then $U(A) > U(B)$
  + Utility function assigns a number
  + Not unique. Two utility functions can represent the same preferences
  + This means utility functions only tell us order, not magnitude. 
  
    $U_1, \text{ & } U_2$ can represent the same preferences while $U_1(A)=1$ and $U_2(A)=1,000$ 
    
  + This is useful in emperical work because prefrences are preserved under a strictly monotonic transformation. 
  
    $U_2(A) = ln(U)$ - same preferences. {sketch ln(x)}
  
  
III. "Goods" More is Better - Nonsatiation

nbn

  